defmodule DerbyLive.Accounts.MagicLinkSender do
  @moduledoc """
  Handles sending magic link authentication emails.

  This module is called by AshAuthentication when a user requests a magic link.
  It constructs the email with the magic link URL and delivers it using Swoosh.
  """
  use DerbyLiveWeb, :verified_routes

  import Swoosh.Email

  alias DerbyLive.Mailer

  @doc """
  Sends a magic link email to the user.

  Called by AshAuthentication's magic link strategy when a user requests
  a login link. The token is a JWT that will be validated when the user
  clicks the link.

  ## Parameters

    * `user_or_email` - Either a User struct or an email string
    * `token` - The JWT token generated by AshAuthentication

  """
  def send(user_or_email, token) do
    email = get_email(user_or_email)
    url = build_magic_link_url(token)

    new()
    |> to(email)
    |> from(configured_sender())
    |> subject("Login to Derby Live")
    |> html_body(build_html(url))
    |> text_body(build_text(url))
    |> Mailer.deliver()

    :ok
  end

  defp get_email(%{email: email}), do: email
  defp get_email(email) when is_binary(email), do: email

  defp build_magic_link_url(token) do
    url(~p"/auth/magic-link/#{token}")
  end

  defp build_html(url) do
    """
    <p>Click the link below to login to Derby Live.</p>

    <p><a href="#{url}">Login</a></p>

    <p>This link will expire in 10 minutes.</p>
    """
  end

  defp build_text(url) do
    """
    Click the link below to login to Derby Live.

    #{url}

    This link will expire in 10 minutes.
    """
  end

  defp configured_sender do
    %{name: name, email: email} = Application.get_env(:derby_live, DerbyLive.Mailer)[:sender]
    {name, email}
  end
end
